import { visit } from 'unist-util-visit';
import type { Element } from 'hast';

export function rehypeZoomMermaid() {
  return (tree: any) => {
    visit(tree, 'element', (node: Element) => {
      // Find pre elements with mermaid class
      if (
        node.tagName === 'pre' &&
        node.properties?.className &&
        Array.isArray(node.properties.className) &&
        node.properties.className.includes('mermaid')
      ) {
        // Add a data attribute to mark it for zoom functionality
        node.properties['data-zoomable'] = 'true';

        // Add zoom styling
        if (!node.properties.style) {
          node.properties.style = '';
        }
        node.properties.style += 'cursor: zoom-in; transition: transform 0.2s ease;';

        // Add title for accessibility
        node.properties.title = 'Click to zoom diagram';
      }

      // Also handle direct SVG elements generated by mermaid
      if (
        node.tagName === 'svg' &&
        node.properties?.id &&
        typeof node.properties.id === 'string' &&
        node.properties.id.startsWith('mermaid')
      ) {
        node.properties['data-zoomable'] = 'true';
        node.properties.style = (node.properties.style || '') + 'cursor: zoom-in; max-width: 100%; height: auto;';
        node.properties.title = 'Click to zoom diagram';
      }
    });
  };
}